return {
    "lukas-reineke/indent-blankline.nvim",
    event = { "BufNewFile", "BufReadPost" },
    config = function()
        require("ibl").setup {
            scope = {
                show_start = false,
                show_end = false,
                injected_languages = true,
                priority = 1000,
                include = {
                    node_type = {
                        ["*"] = {
                            "argument_list",
                            "arguments",
                            "assignment_statement",
                            "Block",
                            "Class",
                            "ContainerDecl",
                            "dictionary",
                            "do_block",
                            "do_statement",
                            "element",
                            "except",
                            "FnCallArguments",
                            "for",
                            "for_statement",
                            "function",
                            "function_declaration",
                            "function_definition",
                            "if_statement",
                            "IfExpr",
                            "IfStatement",
                            "import",
                            "InitList",
                            "list_literal",
                            "method",
                            "object",
                            "ParamDeclList",
                            "repeat_statement",
                            "selector",
                            "SwitchExpr",
                            "table",
                            "table_constructor",
                            "try",
                            "tuple",
                            "type",
                            "var",
                            "while",
                            "while_statement",
                            "with",
                        },
                    },
                },
            },
            exclude = {
                filetypes = {
                    "",
                    "aerial",
                    "alpha",
                    "big_file_disabled_ft",
                    "dashboard",
                    "dotooagenda",
                    "flutterToolsOutline",
                    "fugitive",
                    "git",
                    "gitcommit",
                    "help",
                    "json",
                    "log",
                    "markdown",
                    "NvimTree",
                    "peekaboo",
                    "startify",
                    "TelescopePrompt",
                    "todolist",
                    "txt",
                    "undotree",
                    "vimwiki",
                    "vista",
                },
                buftypes = { "terminal", "nofile", "quickfix", "prompt" },
            }
        }
    end,
}
